AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyInstance: 
    Type: AWS::EC2::Instance
    Properties:
       ImageId: ami-019f9b3318b7155c5
       InstanceType: t2.micro
       KeyName: DevOps Keypair
       AvailabilityZone: us-east-2a